name: Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  Asia:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ASIA
    env:
      TEST_USER: ${{secrets.TEST_USER}}
      TEST_PWD: ${{secrets.TEST_PWD}}
      TEST_APPROVAL_PORTAL: ${{secrets.TEST_APPROVAL_PORTAL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium
      - name: Cleanup with pytest
        run: |
          pytest cleanup_flow_approval.py
  Korea:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: KOREA
    env:
      TEST_USER: ${{secrets.TEST_USER}}
      TEST_PWD: ${{secrets.TEST_PWD}}
      TEST_APPROVAL_PORTAL: ${{secrets.TEST_APPROVAL_PORTAL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium
      - name: Cleanup with pytest
        run: |
          pytest cleanup_flow_approval.py
  Europe:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: EUROPE
    env:
      TEST_USER: ${{secrets.TEST_USER}}
      TEST_PWD: ${{secrets.TEST_PWD}}
      TEST_APPROVAL_PORTAL: ${{secrets.TEST_APPROVAL_PORTAL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium
      - name: Cleanup with pytest
        run: |
          pytest cleanup_flow_approval.py
  US:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: US
    env:
      TEST_USER: ${{secrets.TEST_USER}}
      TEST_PWD: ${{secrets.TEST_PWD}}
      TEST_APPROVAL_PORTAL: ${{secrets.TEST_APPROVAL_PORTAL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium
      - name: Cleanup with pytest
        run: |
          pytest cleanup_flow_approval.py
