# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run scheduled
on:
  schedule:
    - cron:  '*/15 * * * *'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Test with pytest
      env:
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_PWD: ${{secrets.TEST_PWD}}
        TEST_FLOW: ${{secrets.TEST_FLOW}}
        TEST_APPROVAL_PORTAL: ${{secrets.TEST_APPROVAL_PORTAL}}
        TEST_APPROVAL_TEAMS: ${{secrets.TEST_APPROVAL_TEAMS}}
      run: |
        pytest
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: *.png